import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";

import { ProductFilterProvider } from "@/providers/product.filter.provider";

import { FavouriteProvider } from "@/providers/favourite.provider";
import Footer from "@/components/footer";

import { unstable_cache } from "next/cache";

import { CartProvider } from "@/components/carts/cart.context";
import { getFavouritesByUserId } from "@/lib/db/queries/favourites";
import { getCategories, getColors, getSizes } from "@/lib/db/queries/filters";
import { Toaster } from "sonner";
import { getCart } from "@/lib/db/queries/carts";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import { ModalProvider } from "@/providers/modal.provider";
import Modal from "@/components/ui/modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await getCategories();
  const sizes = await getSizes();
  const colors = await getColors();
  const favouriteProducts = await getFavouritesByUserId();
  const cart = await getCart();

  return (
    <html lang="en">
      <body className={inter.className}>
        <ModalProvider>
          <ThemeProvider attribute="class" defaultTheme="system">
            <SessionProvider>
              <Toaster richColors position="top-center" />

              <FavouriteProvider value={favouriteProducts}>
                <CartProvider cart={cart}>
                  <ProductFilterProvider value={{ categories, sizes, colors }}>
                    <Navbar />
                    <div className="min-h-screen">{children}</div>
                    <Footer />
                  </ProductFilterProvider>
                </CartProvider>
              </FavouriteProvider>
            </SessionProvider>
          </ThemeProvider>
        </ModalProvider>
      </body>
    </html>
  );
}
